### ISSUE TITLE
model_utils.my_PAN

### ISSUE THREAD

**Issue by q865516854** [ahstarwab/Violence_Recognition#1]
from model_utils.my_PAN import TA_nopool
from model_utils.my_PAN import Motion_Features_Dilation5
I can't from model_utils import my_PAN and TA_nopool and Motion_Features_Dilation5

**Comment by q865516854** [comment]
import torch_optimizer as torch_optim it is wrong

**Comment by ahstarwab** [comment]
Sorry for confusing you. I just fixed and uploaded a new code. 

You can download "torch_optimizer" with pip.
